### ISSUE TITLE
How should I parse a *.melon file that begins with `RIFF`?

### ISSUE THREAD

**Issue by nijinekoyo** [HNIdesu/MelonBooksDecrypt#1]
I noticed that the code will directly exit when it encounters a file header of `RIFF`. How can I parse this type of file and get the images inside? I noticed that this type of file still has XML content and `file_type` is zip

**Comment by HNIdesu** [comment]
The melon file does indeed start with a `RIFF` header. If the program runs successfully, there should be no error messages. Typically, the program generates an EPUB file. You might want to try unzipping the file and check if it contains any image data.
If you could provide more information or details about your specific case, it would help me understand the situation better and assist you further.

**Comment by nijinekoyo** [comment]
~I noticed that [https://github.com/HNIdesu/MelonBooksDecrypt/blob/main/melondecrypt.py#L42](https://github.com/HNIdesu/MelonBooksDecrypt/blob/main/melondecrypt.py#L42) will exit directly when encountering a `RIFF` file header, and will then report a `key not found` error~

**Comment by nijinekoyo** [comment]
Oh, sorry, I misunderstood. It won't exit here, but after I execute it, it will report an error `key not found`

**Comment by nijinekoyo** [comment]
https://drive.google.com/file/d/1zSeQZnKTiYyJKWQnBtyQdL5OY6PaEyVn/view?usp=sharing
This is an example file, I hope it can help with the problem

**Comment by HNIdesu** [comment]
I’ve submitted a fix in the fix-issue-1 branch that addresses the RIFF parsing failure due to the missing alignment handling. The update includes proper 2-byte alignment handling, which should resolve the parsing errors you encountered.

Could you please test this fix and confirm if it resolves the issue on your end? If everything works as expected, I’ll proceed with merging the changes into the main branch. If you encounter any further issues during testing, please let me know.

**Comment by nijinekoyo** [comment]
I simply tested a few comics and they all passed. 
Thank you very much for your help
